# Generated by Django 5.0.7 on 2024-08-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_alter_comment_like_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
    ]
